package de.augmentia.quad.core.config;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.langchain4j.internal.JsonSchemaElementJsonUtils;
import dev.langchain4j.model.chat.request.json.JsonRawSchema;
import dev.langchain4j.model.chat.request.json.JsonSchema;
import dev.langchain4j.model.chat.request.json.JsonSchemaElement;
import dev.langchain4j.service.output.JsonSchemas;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.util.List;

/**
 * Configuration for structured JSON output from model responses.
 * <p>
 * Use {@link #staticModel(Class)} when the output type is a known Java Record,
 * or {@link #dynamicSchema(String)} when the JSON schema is provided at runtime.
 * The schema is injected into the LLM request via {@code responseFormat}
 * (requires an OpenAI-compatible API that supports structured output).
 * <p>
 * For static models the JSON schema is generated by LangChain4j's
 * {@link JsonSchemas} utility, which correctly handles nested Records,
 * Enums and honors field-level
 * {@code @Description} annotations
 * ({@code dev.langchain4j.model.output.structured.Description}).
 * Java time types are mapped to {@code string}/{@code date-time} schemas.
 */
public record StructuredOutputConfig(
    boolean dynamicSchema,
    Class<?> outputClass,
    String jsonSchema,
    String forcePrompt
) {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static final String DEFAULT_FORCE_PROMPT =
        "You must format the previous response as structured output.";

    /** Creates a config for a statically-typed output class with the default force prompt. */
    public static StructuredOutputConfig staticModel(Class<?> outputClass) {
        return new StructuredOutputConfig(false, outputClass, null, DEFAULT_FORCE_PROMPT);
    }

    /** Creates a config for a statically-typed output class with a custom force prompt. */
    public static StructuredOutputConfig staticModel(Class<?> outputClass, String forcePrompt) {
        return new StructuredOutputConfig(false, outputClass, null, forcePrompt);
    }

    /** Creates a config with a dynamic JSON schema string and the default force prompt. */
    public static StructuredOutputConfig dynamicSchema(String jsonSchema) {
        return new StructuredOutputConfig(true, null, jsonSchema, DEFAULT_FORCE_PROMPT);
    }

    /** Creates a config with a dynamic JSON schema string and a custom force prompt. */
    public static StructuredOutputConfig dynamicSchema(String jsonSchema, String forcePrompt) {
        return new StructuredOutputConfig(true, null, jsonSchema, forcePrompt);
    }

    /** Returns {@code true} if this configuration has a valid output class or non-blank JSON schema. */
    public boolean isEnabled() {
        return (!dynamicSchema && outputClass != null)
            || (dynamicSchema && jsonSchema != null && !jsonSchema.isBlank());
    }

    /**
     * Returns the full {@link JsonSchema} including a schema name.
     * For static models the schema is generated by LangChain4j
     * (nested Records, Enums, {@code @Description} supported);
     * for dynamic models the raw {@code jsonSchema} is wrapped.
     *
     * @return the schema, or {@code null} if this config is not valid
     */
    public JsonSchema effectiveJsonSchema() {
        if (!dynamicSchema) {
            if (outputClass == null) return null;
            return JsonSchemas.jsonSchemaFrom(outputClass)
                .map(schema -> JsonSchema.builder()
                    .name(outputClass.getSimpleName())
                    .rootElement(withTemporalFormats(outputClass, schema.rootElement()))
                    .build())
                .orElse(null);
        }
        if (jsonSchema == null || jsonSchema.isBlank()) return null;
        return JsonSchema.builder()
            .name("structured")
            .rootElement(JsonRawSchema.from(jsonSchema))
            .build();
    }

    /**
     * Returns the JSON schema string.
     * For static models this is the LangChain4j-generated schema rendered to JSON;
     * for dynamic models the raw {@code jsonSchema} is returned unchanged.
     */
    public String effectiveSchema() {
        if (!dynamicSchema) {
            if (outputClass == null) return null;
            return JsonSchemas.jsonSchemaFrom(outputClass)
                .map(js -> writeSchemaString(outputClass, js.rootElement()))
                .orElse(null);
        }
        return jsonSchema;
    }

    // ── LangChain4j schema + temporal type handling ────────────────────

    /**
     * LangChain4j 1.15.0 maps java.time types to plain objects (year/month/day...).
     * We convert them back to string schemas with date/date-time formats so models
     * emit ISO strings that Jackson ({code jsr310}) can deserialize into the Record.
     */
    private JsonSchemaElement withTemporalFormats(Class<?> cls, JsonSchemaElement root) {
        try {
            JsonNode tree = MAPPER.valueToTree(JsonSchemaElementJsonUtils.toMap(root));
            patchTemporal(cls, tree);
            patchRequired(cls, tree);
            return JsonRawSchema.from(MAPPER.writeValueAsString(tree));
        } catch (Exception e) {
            return root;
        }
    }

    private void patchTemporal(Class<?> cls, JsonNode schemaNode) {
        JsonNode propsNode = schemaNode.path("properties");
        if (!propsNode.isObject() || !cls.isRecord()) return;
        ObjectNode props = (ObjectNode) propsNode;
        for (RecordComponent rc : cls.getRecordComponents()) {
            JsonNode prop = props.get(rc.getName());
            if (prop == null) continue;

            String format = temporalFormat(rc.getType());
            if (format != null) {
                props.set(rc.getName(), stringSchema(format));
                continue;
            }
            Class<?> elementType = temporalElementType(rc);
            if (elementType != null && prop.isObject() && prop.has("items")) {
                ((ObjectNode) prop).set("items", stringSchema(temporalFormat(elementType)));
                continue;
            }
            if (rc.getType().isRecord()) {
                patchTemporal(rc.getType(), prop);
            }
        }
    }

    private Class<?> temporalElementType(RecordComponent rc) {
        if (List.class.isAssignableFrom(rc.getType()) || rc.getType().isArray()) {
            var type = rc.getType().isArray()
                ? rc.getType().getComponentType()
                : null;
            if (type == null && rc.getAccessor().getGenericReturnType() instanceof ParameterizedType pt
                && pt.getActualTypeArguments().length > 0
                && pt.getActualTypeArguments()[0] instanceof Class<?> c) {
                type = c;
            }
            return type != null && temporalFormat(type) != null ? type : null;
        }
        return null;
    }

    private static String temporalFormat(Class<?> type) {
        if (type == java.time.LocalDate.class) return "date";
        if (type == java.time.LocalDateTime.class
            || type == java.time.OffsetDateTime.class
            || type == java.time.Instant.class) return "date-time";
        return null;
    }

    private JsonNode stringSchema(String format) {
        var n = MAPPER.createObjectNode();
        n.put("type", "string");
        n.put("format", format);
        return n;
    }

    private String writeSchemaString(Class<?> cls, JsonSchemaElement root) {
        try {
            JsonNode tree = MAPPER.valueToTree(JsonSchemaElementJsonUtils.toMap(root));
            patchTemporal(cls, tree);
            patchRequired(cls, tree);
            return MAPPER.writeValueAsString(tree);
        } catch (Exception e) {
            return root.toString();
        }
    }

    /**
     * Marks all Record components as {@code required} in the generated schema so
     * models cannot silently omit fields ({code Optional} fields stay optional).
     * Nested Records and {@code List<Record>} are handled recursively.
     */
    private void patchRequired(Class<?> cls, JsonNode schemaNode) {
        JsonNode propsNode = schemaNode.path("properties");
        if (!propsNode.isObject() || !cls.isRecord()) return;

        var required = MAPPER.createArrayNode();
        for (RecordComponent rc : cls.getRecordComponents()) {
            if (rc.getType() != java.util.Optional.class) {
                required.add(rc.getName());
            }
            JsonNode prop = propsNode.get(rc.getName());
            if (prop == null) continue;
            Class<?> nested = nestedRecordType(rc);
            if (nested == null) continue;
            if (prop.has("items")) {
                patchRequired(nested, prop.get("items"));
            } else {
                patchRequired(nested, prop);
            }
        }
        ((ObjectNode) schemaNode).set("required", required);
    }

    private Class<?> nestedRecordType(RecordComponent rc) {
        if (rc.getType().isRecord()) return rc.getType();
        Class<?> element = null;
        if (rc.getType().isArray()) {
            element = rc.getType().getComponentType();
        } else if (rc.getAccessor().getGenericReturnType() instanceof ParameterizedType pt
            && pt.getActualTypeArguments().length > 0
            && pt.getActualTypeArguments()[0] instanceof Class<?> c) {
            element = c;
        }
        return element != null && element.isRecord() ? element : null;
    }
}
