package de.augmentia.quad.examples.structured;

import de.augmentia.quad.core.agent.Agent;
import de.augmentia.quad.core.config.ModelFactory;
import de.augmentia.quad.core.config.StructuredInputConfig;
import de.augmentia.quad.core.config.StructuredOutputConfig;
import de.augmentia.quad.core.scope.AgentScope;
import de.augmentia.quad.core.session.AgentSessionState;
import de.augmentia.quad.core.workflow.AgentWorkflowBuilder;
import de.augmentia.quad.core.workflow.AgentWorkflowResult;
import de.augmentia.quad.core.scope.FieldExtractor;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.output.structured.Description;

import java.util.List;

/**
 * Example for typed input and output in agent workflows.
 *
 * <h3>Demo 1: Structured OUTPUT</h3>
 * Shows the JSON schema generated by LangChain4j for Records with
 * {@code @Description} annotations, enums, and nested Records
 * ({@link StructuredOutputConfig#effectiveSchema()}).
 *
 * <h3>Demo 2: Structured INPUT</h3>
 * Shows {@link StructuredInputConfig}: Prompt templates with variables,
 * automatic JSON serialization of Records ({@code {{analysis}}}).
 *
 * <h3>Demo 3: Full pipeline</h3>
 * Two agents connected via {@link AgentWorkflowBuilder}:
 * <pre>
 * AnalyzerAgent  →  System: "You are an analyst..." + User: "{{initialPrompt}}" → TaskAnalysis
 * transform      →  extract only the recommendedTools field
 * PlannerAgent   →  System: "You are an architect..." + User: "Task: {{initialPrompt}}, ..." → ImplementationPlan
 * </pre>
 *
 * <h3>Execution</h3>
 * <pre>
 * cd quad
 * mvn install -pl quad-core -DskipTests -q
 * mvn compile -pl quad-examples -q
 * export OPENAI_API_KEY=sk-...
 * mvn exec:java -pl quad-examples \
 *     -Dexec.mainClass=de.augmentia.quad.examples.structured.StructuredWorkflowExample
 * </pre>
 */
public class StructuredWorkflowExample {

    record TaskAnalysis(
        @Description("Schwierigkeitsgrad: simple, medium oder complex")
        String complexity,

        @Description("Recommended tools for the task")
        List<String> recommendedTools,

        @Description("Estimated effort in hours")
        int estimatedHours) {}

    record ImplementationPlan(
        @Description("Konkrete Umsetzungsschritte in Reihenfolge")
        List<String> steps,

        @Description("Tools, die je Schritt verwendet werden")
        List<String> tools) {}

    static class PipelineAgent extends Agent {
        @Override
        protected AgentSessionState newSessionState() {
            return new AgentSessionState();
        }
    }

    private static final StructuredInputConfig ANALYZE_SYSTEM_MSG = StructuredInputConfig.fromTemplate("""
        Du bist ein erfahrener Software-Analyst.
        Analyze the given task and assess complexity, recommended tools, and estimated effort.
        Antworte mit einem JSON-Objekt mit den Feldern "complexity" (String), "recommendedTools" (Liste<String>) und "estimatedHours" (int).
        """);

    private static final StructuredInputConfig ANALYZE_USER_MSG = StructuredInputConfig.fromTemplate("""
        Analysiere folgenden Task:

        {{initialPrompt}}
        """);

    private static final StructuredInputConfig PLAN_SYSTEM_MSG = StructuredInputConfig.fromTemplate("""
        Du bist ein erfahrener Software-Architekt.
        Erstelle einen detaillierten Implementierungsplan basierend auf der Analyse.
        Antworte mit einem JSON-Objekt mit den Feldern "steps" (Liste<String>) und "tools" (Liste<String>).
        """);

    private static final StructuredInputConfig PLAN_USER_MSG = StructuredInputConfig.fromTemplate("""
        Create an implementation plan for the following task:

        Task: {{initialPrompt}}
        Complexity: {{analysis.complexity}}
        Estimated effort: {{analysis.estimatedHours}} hours
        Available tools: {{tools_for_planner}}
        """);

    public static void main(String[] args) {
        System.out.println("╔══════════════════════════════════════════════════════════╗");
        System.out.println("║   Structured Input & Output for Agent-Workflows          ║");
        System.out.println("╚══════════════════════════════════════════════════════════╝");
        System.out.println();

        demo1OutputSchemas();
        demo2InputTemplate();

        String apiKey = System.getenv("OPENAI_API_KEY");
        if (apiKey == null || apiKey.isBlank()) {
            System.out.println("━━━ Demo 3: Volle Pipeline ━━━");
            System.out.println("Skipped: OPENAI_API_KEY not set.");
            System.out.println("  export OPENAI_API_KEY=sk-...");
            return;
        }
        demo3FullPipeline();
    }

    // ──────────────────────────────────────────────────────────────
    //  Demo 1: Structured OUTPUT — generated JSON schemas
    // ──────────────────────────────────────────────────────────────

    private static void demo1OutputSchemas() {
        System.out.println("━━━ Demo 1: Strukturierter OUTPUT (JSON-Schema-Generierung) ━━━");
        System.out.println();

        var analysisConfig = StructuredOutputConfig.staticModel(TaskAnalysis.class);
        var planConfig = StructuredOutputConfig.staticModel(ImplementationPlan.class);

        System.out.println("Schema for TaskAnalysis (@Description, List<String>, int):");
        System.out.println(analysisConfig.effectiveSchema());
        System.out.println();
        System.out.println("Schema-Name: " + analysisConfig.effectiveJsonSchema().name());
        System.out.println();

        System.out.println("Schema for ImplementationPlan:");
        System.out.println(planConfig.effectiveSchema());
        System.out.println();
    }

    // ──────────────────────────────────────────────────────────────
    //  Demo 2: Structured INPUT — template rendering
    // ──────────────────────────────────────────────────────────────

    private static void demo2InputTemplate() {
        System.out.println("━━━ Demo 2: Strukturierter INPUT (Prompt-Template) ━━━");
        System.out.println();

        var analysis = new TaskAnalysis("complex", List.of("find_files", "grep_search"), 4);

        System.out.println("Analyzer System Message Template:");
        System.out.println(ANALYZE_SYSTEM_MSG.effectiveTemplate());
        System.out.println();
        System.out.println("Analyzer User Message Template:");
        System.out.println(ANALYZE_USER_MSG.effectiveTemplate());
        System.out.println();
        System.out.println("Planner System Message Template:");
        System.out.println(PLAN_SYSTEM_MSG.effectiveTemplate());
        System.out.println();
        System.out.println("Planner User Message Template:");
        System.out.println(PLAN_USER_MSG.effectiveTemplate());
        System.out.println();

        // Scope typical usage: Records are flattened to `key.field` variables,
        // lists/Records are serialized as JSON.
        var scope = new AgentScope("demo-2");
        scope.put("initialPrompt", "REST API for user management");
        scope.put("analysis", analysis);
        scope.put("tools_for_planner", analysis.recommendedTools());

        System.out.println("User message rendered (record fields flattened + JSON serialization):");
        System.out.println(PLAN_USER_MSG.render(scope.templateVariables()));
        System.out.println();
    }

    // ──────────────────────────────────────────────────────────────
    //  Demo 3: Full pipeline — typed agent chain
    // ──────────────────────────────────────────────────────────────

    private static void demo3FullPipeline() {
        System.out.println("━━━ Demo 3: Volle Pipeline (Analyzer → transform → Planner) ━━━");
        System.out.println();

        ChatModel model = ModelFactory.createOpenAiFromEnv();

        PipelineAgent analyzer = new PipelineAgent();
        analyzer.setLlm(model);

        PipelineAgent planner = new PipelineAgent();
        planner.setLlm(model);

        AgentWorkflowBuilder workflow = new AgentWorkflowBuilder()
            // Step 1: Analyze task — system/user messages + typed output
            .step("analyze", analyzer,
                ANALYZE_SYSTEM_MSG, ANALYZE_USER_MSG,
                StructuredOutputConfig.staticModel(TaskAnalysis.class), "analysis")

            // Step 2: pass through only the tools
            .transform("analysis", "tools_for_planner",
                value -> FieldExtractor.extract(value, "recommendedTools"))

            // Step 3: Plan with separate system/user messages + typed output
            .step("plan", planner,
                PLAN_SYSTEM_MSG, PLAN_USER_MSG,
                StructuredOutputConfig.staticModel(ImplementationPlan.class), "plan");

        String task = args0();
        System.out.println("Task: " + task);
        System.out.println();

        AgentWorkflowResult result = workflow.execute(task);

        // ── Read results as typed from the scope ──
        Object analysisObj = result.scope().get("analysis");
        System.out.println("Analyse (typisiert):");
        if (analysisObj instanceof TaskAnalysis analysis) {
            System.out.println("  Complexity:  " + (analysis.complexity() != null ? analysis.complexity() : "?"));
            System.out.println("  Tools:        " + (analysis.recommendedTools() != null ? analysis.recommendedTools() : "?"));
            System.out.println("  Aufwand:      " + analysis.estimatedHours() + "h");
        } else {
            System.out.println("  Roh (keine Deserialisierung): " + analysisObj);
        }
        System.out.println();

        Object planObj = result.scope().get("plan");
        System.out.println("Plan (typisiert):");
        if (planObj instanceof ImplementationPlan plan && plan.steps() != null) {
            for (int i = 0; i < plan.steps().size(); i++) {
                System.out.printf("  %d. %s%n", i + 1, plan.steps().get(i));
            }
            System.out.println("  Tools: " + (plan.tools() != null ? plan.tools() : "?"));
        } else {
            System.out.println("  Roh (LLM hat Pflichtfelder nicht geliefert):");
            System.out.println("  " + result.finalStructuredOutput());
        }
        System.out.println();

        System.out.println("Finale Antwort des Planners:");
        System.out.println(result.finalText());
        System.out.println();
    }

    private static String args0() {
        return "Create a REST API for user management";
    }
}