apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quad.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "quad.labels" . | nindent 4 }}
data:
  QUARKUS_PROFILE: {{ .Values.quarkus.env.QUARKUS_PROFILE | quote }}
  QUARKUS_HTTP_PORT: {{ .Values.quarkus.env.QUARKUS_HTTP_PORT | quote }}
