{{- if .Values.postgresql.cloudSqlProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quad.fullname" . }}-sa
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "quad.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.postgresql.cloudSqlProxy.gcpServiceAccount | default "" | quote }}
{{- end }}
